### ISSUE TITLE
Pan/zoom not working due to instanceof failing

### ISSUE THREAD

**Issue by otoomey** [nicolaspanel/three-orbitcontrols-ts#1]
Because you have bundled a copy of Three.js library in your project, `instanceof` fails when I pass a camera I made from another copy of Three.js (that I installed using npm and loaded with typings). Please consider requiring the installation of three.js separately from your orbital-controls package, and then using that one instead.

Or, a quick and non-breaking option would be to change the lines similar to the following:
`if (this.object instanceof THREE.PerspectiveCamera) { ... `
to
`if (this.object.type === "PerspectiveCamera") { ...`

'Orbiting' works without the fix, but zoom and pan are both broken with the following message (I'm just showing the zoom one here):
`WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.`

In case there is confusion, here is a tree of what is happening:

- node_modules
  - @types
      - three (definition file. points to the following three library)
  - three
      - three (standard npm library, the one that I use throughout my project)
  - three-orbitcontrols-ts (your library)
      - three (the same three library, but you have bundled ANOTHER copy just for your module)
      - dist (your orbiting controls code)

**Comment by otoomey** [comment]
I've looked at it a bit more, and I have found that you can simply solve the problem by replacing:
`import * as THREE from 'three';`
with
`import * as THREE from '../../three';`

and then make sure you have `three.js` installed via npm.

Loading three.js only once instead of twice saves 4MB of RAM.

**Comment by phile314-fh** [comment]
I have got the zoom working by using yarn instead and setting the threejs version used by three-orbitcontrols-ts inside the yarn.lock file to the same one we are using in our own code. This makes zooming work for us and also gets rid of the additional threejs copy inside of the three-orbitcontrols-ts module. The main drawback is that I had to fiddle manually with the lockfile...

**Comment by chrispellett** [comment]
For anyone interested, I think I got this working by using  NPM shrinkwrap functionality (adapted from:  https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions)

Specifically, after installing the module I opened my shrinkwrap file, found the three-orbitcontrols-ts entry:
- I then removed the dependencies section completely
- Then I deleted the three-orbitcontrols-ts folder from node_modules
- Then I ran npm install
- Reloading the shrinkwrap file I could see the dependencies were still removed

After that, the appropriate THREE dependency (appears to) have been loaded

**Comment by Reintjuu** [comment]
@chrispellett Could you share your shrinkwrap file?

**Comment by sethk** [comment]
Seems like `three.js` is solving this problem by using type identity properties such as `isPerspectiveCamera` in their example code. At least that's the case in 0.91.0.

**Comment by Sheldan** [comment]
would another option not be to remove the own bundled dependency of threejs and instead rely, that the user has its own?
Although this library uses an older version of threejs, is there an updated planned to address this?

**Comment by sk0va** [comment]
@nicolaspanel is there any plans to update the npm package?

**Comment by pirumpi** [comment]
Can someone publish this fix to NPM?

**Comment by alecmolloy** [comment]
bumping^

For anyone else encountering this problem, to unblock yourself you can just reference this git repo directly in your package.json:
```json
  "dependencies": {
    "three-orbitcontrols-ts": "git+https://git@github.com/nicolaspanel/three-orbitcontrols-ts.git",
  }
```
