### ISSUE TITLE
Should Three be defined as a peer dependency?

### ISSUE THREAD

**Issue by computerlove** [nicolaspanel/three-orbitcontrols-ts#3]
Hi, 
I'm testing `three-orbitcontrols-ts`, and having problems zooming.
The scene is set up with `THREE.PerspectiveCamera`, and when dollyIn/Out is called `this.object instanceof THREE.PerspectiveCamera` is false. 

When evaluating this.object.constructor it points to a version of Three pulled inn by orbitcontrols, while THREE.PerspectiveCamera points to the main version.

Should Three be a peer-dependecy so that a separate version is not included?

**Comment by Sheldan** [comment]
This is basically the same issue as issue #1 and should be fixed if #4 is released.
