### ISSUE TITLE
Where is saveState?

### ISSUE THREAD

**Issue by rtm** [nicolaspanel/three-orbitcontrols-ts#6]
The latest distrubution of three.js contains a method on this API called `saveState`, which seems to be missing here, unless I'm missing something.

**Comment by MichalHe** [comment]
I've checked the source and you're right - the method `saveState` is currently missing. 
Let me know if you find anything that should be implemented, but is currently missing.

**Comment by rtm** [comment]
@MichalHe Many thanks.

Meanwhile, I came up with the horrible, horrible solution documented [here](https://github.com/Microsoft/TypeScript/issues/10178#issuecomment-409320281) which doesn't require a fork of the code, and am using it so far with no ill effects.
